import { Injectable } from '@nestjs/common';
import type { GitHubPRDecision, GitHubTestStatus } from '@prisma/client';
import type { GitHubReviewSummary } from './github-review.types';

@Injectable()
export class GitHubReportService {
  generate(input: {
    repository: string;
    pullRequestNumber: number;
    headSha: string;
    threshold: number;
    decision: GitHubPRDecision;
    testStatus: GitHubTestStatus;
    review: GitHubReviewSummary;
  }) {
    const issueSections = input.review.issues.length
      ? input.review.issues
          .map((issue) => {
            const location = issue.line
              ? `${issue.path}:${issue.line}`
              : issue.path;
            return [
              `### ${issue.severity.toUpperCase()}: ${escapeMarkdown(
                issue.title,
              )}`,
              `**File:** \`${escapeInlineCode(location)}\``,
              escapeMarkdown(issue.description),
              issue.suggestion
                ? `**Suggested fix:** ${escapeMarkdown(issue.suggestion)}`
                : undefined,
            ]
              .filter(Boolean)
              .join('\n\n');
          })
          .join('\n\n')
      : 'No actionable issues were identified in the reviewed context.';
    const strengths = input.review.strengths.length
      ? input.review.strengths
          .slice(0, 12)
          .map(
            (item) =>
              `- \`${escapeInlineCode(item.path)}\`: ${escapeMarkdown(
                item.text,
              )}`,
          )
          .join('\n')
      : '- No explicit strengths were returned by the review model.';

    return [
      '# TaskFlow AI Pull Request Review',
      '',
      `Repository: \`${escapeInlineCode(input.repository)}\``,
      `Pull request: #${input.pullRequestNumber}`,
      `Reviewed head: \`${escapeInlineCode(input.headSha.slice(0, 12))}\``,
      '',
      '## Verdict',
      '',
      '| AI score | Required | Decision | Tests |',
      '| ---: | ---: | --- | --- |',
      `| ${input.review.score}/100 | ${input.threshold}/100 | ${formatDecision(
        input.decision,
      )} | ${input.testStatus.toLowerCase()} |`,
      '',
      escapeMarkdown(input.review.summary),
      '',
      `Reviewed ${input.review.filesReviewed} file(s); skipped ${input.review.filesSkipped} file(s) to avoid binary/generated content and stay inside the configured context budget.`,
      '',
      '## Findings',
      '',
      issueSections,
      '',
      '## Strengths',
      '',
      strengths,
      '',
      '## Next Steps',
      '',
      input.decision === 'APPROVED'
        ? 'The reviewed changes meet the configured score threshold. A human reviewer should still confirm product intent and deployment readiness.'
        : 'Address the high-impact findings, push a new commit, and run the AI review again. The next report will be stored as a new version.',
      '',
      '_Generated by TaskFlow. AI review supports human review and does not replace it._',
    ].join('\n');
  }
}

function escapeMarkdown(value: string) {
  return value
    .replace(/[<>]/g, '')
    .replaceAll(String.fromCharCode(0), '')
    .slice(0, 5000);
}

function escapeInlineCode(value: string) {
  return value.replace(/`/g, '').slice(0, 500);
}

function formatDecision(decision: GitHubPRDecision) {
  return decision
    .toLowerCase()
    .split('_')
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(' ');
}
